program_options:
    tray: auto
    menu: flat
    automount: false
    notify: true
    password_cache: false
    file_manager: xdg-open
    terminal: alacritty --working-directory
    password_prompt: builtin:gui

notifications:
    device_mounted: false
    device_unmounted: false
    device_added: false
    device_removed: -1
    device_unlocked: -1
    device_locked: -1
    job_failed: -1

quickmenu_actions: all

notification_actions:
    device_mounted: []
    device_added: []
    job_failed: []

icon_names:
    media: [drive-removable-media]
    browse: [document-open]
    terminal: [utilities-terminal]
    mount: [udiskie-mount]
    unmount: [udiskie-unmount]
    unlock: [object-unlocked]
    lock: [object-locked]
    eject: [media-eject]
    detach: [udiskie-detach]
    quit: [application-exit]
    forget_password: [edit-delete]
    clear_passwords: [edit-delete]
    delete: [media-eject]
    losetup: [udiskie-mount]
