set $mod Mod4
set $alt Mod1

bindsym XF86AudioRaiseVolume exec --no-startup-id ~/.local/bin/scripts.d/notify.sh pulseaudio inc
bindsym XF86AudioLowerVolume exec --no-startup-id ~/.local/bin/scripts.d/notify.sh pulseaudio dec
bindsym XF86AudioMute exec --no-startup-id ~/.local/bin/scripts.d/notify.sh pulseaudio toggle

bindsym XF86MonBrightnessUp exec --no-startup-id ~/.local/bin/scripts.d/notify.sh backlight inc
bindsym XF86MonBrightnessDown exec --no-startup-id ~/.local/bin/scripts.d/notify.sh backlight dec

bindsym XF86TouchpadOn exec --no-startup-id ~/.local/bin/scripts.d/notify.sh touchpad on
bindsym XF86TouchpadOff exec --no-startup-id ~/.local/bin/scripts.d/notify.sh touchpad off

bindsym XF86RFKill exec --no-startup-id ~/.local/bin/scripts.d/notify.sh airplane

bindsym $mod+Left focus left
bindsym $mod+Right focus right
bindsym $mod+Down focus down
bindsym $mod+Up focus up

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Right move right
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up

bindsym $mod+h split h
bindsym $mod+v split v
bindsym $mod+f fullscreen toggle

bindsym $mod+s layout stacking
bindsym $mod+t layout tabbed
bindsym $mod+n layout toggle split

bindsym $mod+minus scratchpad show, move position center
bindsym $mod+Shift+minus, floating enable, resize set 1900 1000, move scratchpad

bindsym $mod+space focus mode_toggle
bindsym $mod+Shift+space floating toggle

bindsym $mod+p focus parent
bindsym $mod+c focus child

bindsym $alt+Tab workspace back_and_forth

bindsym $mod+1 workspace number 1
bindsym $mod+2 workspace number 2
bindsym $mod+3 workspace number 3
bindsym $mod+4 workspace number 4
bindsym $mod+5 workspace number 5
bindsym $mod+6 workspace number 6
bindsym $mod+7 workspace number 7
bindsym $mod+8 workspace number 8
bindsym $mod+9 workspace number 9
bindsym $mod+0 workspace number 10

bindsym $mod+Shift+1 move container to workspace number 1
bindsym $mod+Shift+2 move container to workspace number 2
bindsym $mod+Shift+3 move container to workspace number 3
bindsym $mod+Shift+4 move container to workspace number 4
bindsym $mod+Shift+5 move container to workspace number 5
bindsym $mod+Shift+6 move container to workspace number 6
bindsym $mod+Shift+7 move container to workspace number 7
bindsym $mod+Shift+8 move container to workspace number 8
bindsym $mod+Shift+9 move container to workspace number 9
bindsym $mod+Shift+0 move container to workspace number 10

bindsym --release $mod+Shift+q kill
bindsym --release button2 kill

bindsym $mod+Shift+r reload
bindsym $mod+Shift+Control+r restart

bindsym $mod+x exec --no-startup-id xfce4-clipman-history
bindsym $mod+d exec --no-startup-id ~/.local/bin/scripts.d/rofi.sh drun
bindsym $mod+l exec --no-startup-id ~/.local/bin/scripts.d/locker.sh
bindsym $mod+Return exec --no-startup-id alacritty --config-file ~/.config/alacritty/alacritty.toml
bindsym $mod+Print exec --no-startup-id scrot --quality 100

mode "R" {
    bindsym Left resize shrink width 5px or 5ppt
    bindsym Right resize grow width 5px or 5ppt
    bindsym Down resize shrink height 5px or 5ppt
    bindsym Up resize grow height 5px or 5ppt
    bindsym Escape mode "default"
}
    bindsym $mod+r mode "R"
