for_window [instance="arandr" class="Arandr"] floating enable, border normal 5, move position center
for_window [instance="Browser" class="firefox"] floating enable, border normal 5, move position center
for_window [instance="gnome-calculator" class="gnome-calculator"] floating enable, border normal 5, move position center
for_window [instance="nm-connection-editor" class="Nm-connection-editor"] floating enable, border normal 5, move position center
for_window [instance="pavucontrol" class="pavucontrol"] floating enable, border normal 5, move position center
for_window [instance="Places" class="firefox"] floating enable, border normal 5, move position center
