Section "InputClass"
        Identifier "keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "tr,tr"
        Option "XkbVariant" ",f"
        Option "XkbOptions" "grp:alt_space_toggle"
        Option "AutoRepeat" "330 40"
EndSection
