# https://man.archlinux.org/man/xkeyboard-config-2.7.en
Section "InputClass"
        Identifier "keyboard"
        MatchIsKeyboard "on"
        Option "AutoRepeat" "330 40"
        Option "XkbLayout" "tr,tr"
        Option "XkbOptions" "grp:alt_space_toggle"
        Option "XkbVariant" ",f"
EndSection
