# https://xkeyboard-config.freedesktop.org/doc/config/
Section "InputClass"
        Identifier "keyboard"
        MatchIsKeyboard "on"
        Option "AutoRepeat" "330 40"
        Option "XkbLayout" "tr,tr"
        Option "XkbOptions" "grp:alt_space_toggle"
        Option "XkbVariant" ",f"
EndSection
