bar {
    #status_command i3status

    mode hide
    hidden_state hide
    modifier none

    bindsym button2 nop
    bindsym button3 nop
    bindsym button4 nop
    bindsym button5 nop
    bindsym button6 nop
    bindsym button7 nop

    id bar-2

    position top

    tray_output primary

    tray_padding 0

    #separator_symbol " "

    workspace_buttons no

    #workspace_min_width 50

    #strip_workspace_numbers no
    #strip_workspace_name no

    binding_mode_indicator no

    colors {
        background              "#000000"
        statusline              "#000000"
        separator               "#000000"

        focused_workspace       "#000000" "#000000" "#000000"
        active_workspace        "#000000" "#000000" "#000000"
        inactive_workspace      "#000000" "#000000" "#000000"
        urgent_workspace        "#000000" "#000000" "#000000"
        binding_mode            "#000000" "#000000" "#000000"
    }

    padding 20 0 20 0
}
