[greeter]
active-monitor=#cursor
allow-debugging=false
background=#000000
clock-format=%H:%M:%S
default-user-image=#anjuta
font-name=JetBrains Mono 12
hide-user-image=false
icon-theme-name=Papirus
indicators=~session;~spacer;~clock;~spacer;~power
panel-position=top
screensaver-timeout=0
