[greeter]
#theme-name=
icon-theme-name=Papirus
#cursor-theme-name=
#cursor-theme-size=
background=#000000
#user-background=
#transition-duration=
#transition-type=
font-name=JetBrains Mono 12
#xft-antialias=
#xft-dpi=
#xft-hintstyle=
#xft-rgba=
active-monitor=#cursor
#position=
default-user-image=#anjuta
#hide-user-image=
#round-user-image=
#highlight-logged-user=
#panel-position=
#clock-format=
indicators=~session;~spacer;~clock;~spacer;~power
#keyboard-layouts=
#a11y-states=
#keyboard=
#keyboard-position=
#reader=
#at-spi-enabled=
#allow-debugging=
screensaver-timeout=0
#default-session=
