[LightDM]
run-directory=/run/lightdm

[Seat:*]
allow-guest = false
autologin-guest = false
greeter-allow-guest = false
greeter-hide-users = true
greeter-session = lightdm-gtk-greeter
greeter-show-manual-login = true
session-wrapper=/etc/lightdm/Xsession
