[greeter]
active-monitor = #cursor
allow-debugging = false
clock-format = %H:%M:%S
default-user-image = #anjuta
font-name = JetBrains Mono 10
icon-theme-name = Papirus
indicators = ~session;~spacer;~clock;~spacer;~power
screensaver-timeout = 0
