#!/bin/bash

if [ -n "$1" ]
then
    coproc {
        $1 >& /dev/null
    }
    exit
fi

while read -r string icon permanent
do
    echo -e "$string\0icon\x1f$icon\x1fpermanent\x1f$permanent"
done << EOF
poweroff system-shut-down true
reboot system-restart true
EOF
