#!/bin/bash

if [ -n "$1" ]
then
    coproc {
        $1 >& /dev/null
    }
    exit
fi

while read -r string icon
do
    echo -e "$string\0icon\x1f$icon\x1fpermanent\x1ftrue"
done << EOF
poweroff system-shut-down
reboot system-restart
EOF
