context.modules=[
    {
        name=libpipewire-module-loopback
        args={
            node.description="Single Audio Channel"
            capture.props={
                audio.position=[ MONO ]
                filter.smart=true
                media.class="Audio/Sink"
            }
            playback.props={
                audio.position=[ MONO ]
                node.dont-reconnect=false
                node.passive=true
            }
        }
    }
]
