# Blur background of semi-transparent / ARGB windows.
# Can be set per-window using rules.
#
# Default: false
blur-background=false;

# Blur background of windows when the window frame is not opaque.
# Implies:
#    blur-background
#
# Default: false
blur-background-frame=false;

# Use fixed blur strength rather than adjusting according to window opacity.
#
# Default: false
blur-background-fixed=false;
