# The directory where the user files with the failure records are kept.
dir=/var/run/faillock
#
# Will log the user name into the system log if the user is not found.
# audit
#
# Don't print informative messages to the user.
silent
#
# Don't log informative messages via syslog(3).
# no_log_info
#
# Only track failed user authentications attempts for local users in /etc/passwd and ignore centralized users.
# local_users_only
#
# Don't enforce a delay after authentication failures.
# nodelay
#
# Deny access if the number of consecutive authentication failures for this user during the recent interval exceeds n.
deny=5
#
# The length of the interval during which the consecutive authentication failures must happen for the user account lock out is n seconds.
fail_interval=900
#
# The access will be re-enabled after n seconds after the lock out.
unlock_time=600
#
# Root account can become locked as well as regular accounts.
# even_deny_root
#
# Allow access after n seconds to root account after the account is locked.
# root_unlock_time=900
