alias 0='xsel -bi'
alias 1='xsel -bo'
alias cal='cal --color=auto -m'
alias cat='bat --color=auto -pp --theme="Solarized (dark)"'
alias diff='diff --color=auto'
alias grep='grep --color=auto --exclude-dir={.git,.venv,venv}'
alias ls='ls --color=auto --classify=always --quoting-style=escape --time-style=iso'
alias rm='trash-put -v'
alias test-speaker='speaker-test -c 2 -t wav -l 1'
alias vim='vim -X'
alias which='whence -a'
