alias 0='xsel -bi'
alias 1='xsel -bo'
alias cal='cal --color=auto --monday --year'
alias diff='diff --color=auto'
alias grep='grep --color=auto --exclude-dir={.git,.idea,.venv,venv}'
alias la='ls -a'
alias li='ls -i'
alias ll='ls -l'
alias lr='ls -r'
alias ls='ls --color=auto --classify=always --quoting-style=escape --time-style=long-iso'
alias pacman='pacman --color=auto'
alias sudo='sudo '
alias test-speaker='speaker-test -c 2 -t wav -l 1'
alias vim='vim -X'
alias which='whence -a'
