alias 0='xsel -bi'
alias 1='xsel -bo'
alias cal='cal --color=auto --monday'
alias cat='bat'
alias diff='diff --color=auto'
alias grep='GREP_COLORS=sl=0:cx=0:mt=31:ms=31:mc=31:fn=35:ln=32:bn=33:se=36 grep --color=auto --exclude-dir={.git,.venv,venv}'
alias la='ls -a'
alias li='ls -i'
alias ll='ls -l'
alias lr='ls -r'
alias ls='ls --color=auto --classify=always --quoting-style=escape --time-style=long-iso'
alias pacman='pacman --color=auto'
alias q='qalc'
alias rm='trash-put -v'
alias sudo='sudo '
alias test-speaker='speaker-test -c 2 -t wav -l 1'
alias vim='vim -X'
alias which='whence -va'
