typeset -gA ZSH_HIGHLIGHT_STYLES=(
    [unknown-token]=fg=red
    [reserved-word]=fg=yellow
    [alias]=fg=green
    [suffix-alias]=none
    [global-alias]=none
    [builtin]=fg=green
    [function]=fg=green
    [command]=fg=green
    [precommand]=fg=green
    [commandseparator]=none
    [hashed-command]=none
    [autodirectory]=underline
    [path]=underline
    [path_pathseparator]=underline
    [path_prefix]=underline
    [path_prefix_pathseparator]=underline
    [globbing]=fg=blue
    [history-expansion]=fg=blue
    [command-substitution]=none
    [command-substitution-unquoted]=none
    [command-substitution-quoted]=none
    [command-substitution-delimiter]=fg=magenta
    [command-substitution-delimiter-unquoted]=fg=magenta
    [command-substitution-delimiter-quoted]=fg=magenta
    [process-substitution]=none
    [process-substitution-delimiter]=fg=magenta
    [arithmetic-expansion]=fg=magenta
    [single-hyphen-option]=none
    [double-hyphen-option]=none
    [back-quoted-argument]=none
    [back-quoted-argument-unclosed]=none
    [back-quoted-argument-delimiter]=fg=magenta
    [single-quoted-argument]=fg=yellow
    [single-quoted-argument-unclosed]=fg=yellow
    [double-quoted-argument]=fg=yellow
    [double-quoted-argument-unclosed]=fg=yellow
    [dollar-quoted-argument]=fg=yellow
    [dollar-quoted-argument-unclosed]=fg=yellow
    [rc-quote]=none
    [dollar-double-quoted-argument]=fg=cyan
    [back-double-quoted-argument]=fg=cyan
    [back-dollar-quoted-argument]=fg=cyan
    [assign]=none
    [redirection]=fg=yellow
    [comment]=none
    [named-fd]=none
    [numeric-fd]=none
    [arg0]=fg=green
    [default]=none
)
