[Login]
IdleAction=ignore
KillUserProcesses=yes
HandleHibernateKey=ignore
HandleHibernateKeyLongPress=ignore
HandleLidSwitch=ignore
HandleLidSwitchDocked=ignore
HandleLidSwitchExternalPower=ignore
HandlePowerKey=ignore
HandlePowerKeyLongPress=ignore
HandleRebootKey=ignore
HandleRebootKeyLongPress=ignore
HandleSecureAttentionKey=ignore
HandleSuspendKey=ignore
HandleSuspendKeyLongPress=ignore
HibernateKeyIgnoreInhibited=no
LidSwitchIgnoreInhibited=no
PowerKeyIgnoreInhibited=no
RebootKeyIgnoreInhibited=no
SuspendKeyIgnoreInhibited=no
