bar {
    # The specified command will be passed to sh -c.
    i3bar_command i3bar

    # Run a program and display every line of its stdout output on the right hand side of the bar.
    status_command i3status

    # Have i3bar be visible permanently at one edge of the screen.
    mode dock
    hidden_state hide
    modifier none

    # Specifies a command to run when a button was pressed on i3bar to override the default behavior.
    bindsym button2 exec --no-startup-id x-center notify volume tog
    bindsym button3 exec --no-startup-id x-center notify volume inc
    bindsym button4 nop
    bindsym button5 exec --no-startup-id x-center notify volume dec
    bindsym button6 nop
    bindsym button7 nop
    bindsym button8 nop
    bindsym button9 nop

    # Specifies the bar ID for the configured bar instance.
    id bar-1

    # This option determines in which edge of the screen i3bar should show up.
    position top

    # Show tray icons on the primary monitor.
    tray_output primary

    # Padding for the upper, lower and right-hand side of the tray area and between the individual icons.
    tray_padding 0 px

    # Specifies the font to be used in the bar.
    font pango:JetBrains Mono NL 12

    # Specifies a custom symbol to be used for the separator.
    separator_symbol " "

    # Specifies whether workspace buttons should be shown or not.
    workspace_buttons yes

    # This option specifies the minimum width for workspace buttons.
    workspace_min_width 90 px

    # Specifies whether workspace numbers should be displayed within the workspace buttons.
    strip_workspace_numbers no
    strip_workspace_name no

    # Specifies whether the current binding mode indicator should be shown or not.
    binding_mode_indicator no

    # Make i3bar higher, and/or add padding to the left and right side of i3bar.
    padding 15px 0px 15px 0px

    colors {
        background #000000
        statusline #FFFFFF
        separator  #FFFFFF

        focused_workspace  #2F4F4F #2F4F4F #000000
        active_workspace   #301934 #301934 #000000
        inactive_workspace #000000 #000000 #FFFFFF
        urgent_workspace   #FF0000 #FF0000 #000000
        binding_mode       #2F4F4F #2F4F4F #000000
    }
}
