bar {
    # https://i3wm.org/docs/userguide.html#_i3bar_command
    i3bar_command i3bar

    # https://i3wm.org/docs/userguide.html#status_command
    status_command i3status

    # https://i3wm.org/docs/userguide.html#_display_mode
    mode dock
    hidden_state hide
    modifier none

    # https://i3wm.org/docs/userguide.html#_mouse_button_commands
    bindsym button2 nop
    bindsym button3 nop
    bindsym button4 nop
    bindsym button5 nop
    bindsym button6 nop
    bindsym button7 nop
    bindsym button8 nop
    bindsym button9 nop

    # https://i3wm.org/docs/userguide.html#_bar_id
    id bar-1

    # https://i3wm.org/docs/userguide.html#i3bar_position
    position top

    # https://i3wm.org/docs/userguide.html#_tray_output
    tray_output primary

    # https://i3wm.org/docs/userguide.html#_tray_padding
    tray_padding 0 px

    # https://i3wm.org/docs/userguide.html#_font
    font pango:JetBrains Mono NL 14

    # https://i3wm.org/docs/userguide.html#_custom_separator_symbol
    separator_symbol " "

    # https://i3wm.org/docs/userguide.html#_workspace_buttons
    workspace_buttons yes

    # https://i3wm.org/docs/userguide.html#_minimal_width_for_workspace_buttons
    workspace_min_width 100 px

    # https://i3wm.org/docs/userguide.html#_strip_workspace_numbers_name
    strip_workspace_numbers no
    strip_workspace_name no

    # https://i3wm.org/docs/userguide.html#_binding_mode_indicator
    binding_mode_indicator yes

    # https://i3wm.org/docs/userguide.html#i3bar_padding
    padding 15px 0px 15px 0px

    # https://i3wm.org/docs/userguide.html#_colors
    colors {
        background #000000
        statusline #888888
        separator  #1f1f1f

        focused_workspace  #1f1f1f #1f1f1f #ffffff
        active_workspace   #301934 #301934 #ffffff
        inactive_workspace #000000 #000000 #ffffff
        urgent_workspace   #880808 #880808 #000000
        binding_mode       #000000 #000000 #880808
    }
}
