font pango:Noto Sans Mono 12

# This option determines which border style new windows will have.
default_border normal 0

# This option determines which border style new windows will have.
default_floating_border normal 5

# Hide container borders adjacent to the screen edges.
hide_edge_borders both
