font pango:Noto Sans Mono 12

title_align left

default_border $default_border

default_floating_border $default_floating_border

hide_edge_borders both

for_window [all] title_format %title

for_window [all] title_window_icon no
