font pango:Noto Sans Mono 14

title_align left

default_border normal 0

default_floating_border normal 5

hide_edge_borders both

for_window [all] title_format %title

for_window [all] title_window_icon no

for_window [floating] move position center
