# Controls the kernel's behavior when a hung task is detected.
kernel.hung_task_panic=1
# When a task in D state did not get scheduled for more than this value report a warning.
kernel.hung_task_timeout_secs=60
# The value in this file represents the number of seconds the kernel waits before rebooting on a panic.
kernel.panic=0
# It is a 'magical' key combo you can hit which the kernel will respond to regardless of whatever else it is doing, unless it is completely locked up.
kernel.sysrq=0
